<script lang="ts">
  import { fade, fly } from 'svelte/transition';
  import { goto } from '$app/navigation';
  import { createEventDispatcher, onMount } from 'svelte';
  import { toast } from '$lib/utils/toast';

  import { runProbeJob, type ProbeRunRequest } from '$lib/api/probes';
  import { pollProbeJob } from '$lib/features/jobs/probe-polling';
  import RunProbeButton from '$lib/components/common/RunProbeButton.svelte';
  import CredentialsFields from '$lib/components/common/CredentialsFields.svelte';
  import { resolveCredentials } from '$lib/auth/credentials-service';
  import { isValidHostname, isValidIPv4 } from '$lib/utils/host-validate';
  import { buildStorageEndpointConnectProbeRequest } from '$lib/probe/probe-builders';
  import { syncStorageRootDiscoveryForEndpoint } from '$lib/probe/probe-runner';
  import { extractDomainFromUsername } from '$lib/probe/storage-endpoint-probe';
  import { jobsStore } from '$lib/stores/app/jobs.store';

  import {
    createStorageEndpoint,
    listStorageEndpoints,
    type StorageEndpointOverview
  } from '$lib/api/storage-endpoints';
  import { createStorageRoot } from '$lib/api/storage-roots';
  import { listZones, type ZoneOverview } from '$lib/api/zones';
  import { listIdentitySources, type IdentitySourceListItem } from '$lib/api/identity-sources';

  /* =========================================================
     CONFIGURATION
  ========================================================= */
  export let variant: 'page' | 'modal' = 'modal';
  export let onDone: (() => void) | null = null;
  let isPage = variant === 'page';
  $: isPage = variant === 'page';

  // Optional prefill from parent pages (ex: /admin/zones)
  export let initialZoneId: number | null = null;
  export let lockZone = false;

  const requiresIdentitySource = false;
  const managedRootBadgeLabel = 'Integrated';
  const availableRootBadgeLabel = 'Available';

  const dispatch = createEventDispatcher<{
    done: { id: number; created_roots: number; failed_roots: number };
  }>();

  /* =========================================================
     STATE
  ========================================================= */
  let step = 1;
  let direction: 'forward' | 'back' = 'forward';

  let model: {
    protocol: 'smb';

    name?: string;
    description?: string;

    host?: string;
    port?: number;

    username?: string;

    /**
     * 🔐 UI ONLY — never sent directly
     */
    password?: string;

    /**
     * Generated by backend secret management.
     */
    secret_ref?: string | null;

    roots?: string[];
    zone_id?: number | null;
    identity_source_id?: number | null;
  } = {
    protocol: 'smb',
    roots: [],
    secret_ref: null,
    zone_id: null,
    identity_source_id: null
  };

  let zones: ZoneOverview[] = [];
  let zonesLoading = false;
  let zonesError: string | null = null;

  type IdentitySourceOption = IdentitySourceListItem;

  let identitySources: IdentitySourceOption[] = [];
  let identitySourcesLoading = false;
  let identitySourcesError: string | null = null;
  let existingEndpoints: StorageEndpointOverview[] = [];

  const wizardProbeJobInput = () => ({
    entityType: 'storage-endpoint-wizard',
    entityId: `${String(model.host ?? 'new')}::${String(model.name ?? 'endpoint')}`,
    action: 'probe'
  } as const);

  const wizardDiscoveryJobInput = () => ({
    entityType: 'storage-endpoint-wizard',
    entityId: `${String(model.host ?? 'new')}::${String(model.name ?? 'endpoint')}`,
    action: 'discovery'
  } as const);

  onMount(async () => {
    zonesLoading = true;
    identitySourcesLoading = true;
    zonesError = null;
    identitySourcesError = null;
    try {
      zones = await listZones(fetch);
      existingEndpoints = await listStorageEndpoints(fetch);
      const rows = await listIdentitySources(fetch);
      identitySources = rows as IdentitySourceListItem[];

      // Prefill zone if provided
      if (initialZoneId !== null && initialZoneId !== undefined) {
        model.zone_id = initialZoneId;
      }
    } catch (e) {
      const message = e?.message ?? 'Unable to load wizard data.';
      zonesError = message;
      identitySourcesError = message;
    } finally {
      zonesLoading = false;
      identitySourcesLoading = false;
    }
  });

  $: activeAdIdentitySources = identitySources.filter((s) => {
    const kind = String(s?.type ?? '').trim().toUpperCase();
    const active = s?.is_active !== false;
    return active && (kind === 'AD' || kind === 'LDAP' || kind === 'LDAPS');
  });

  /* =========================================================
     VALIDATION
  ========================================================= */

  let showPassword = false;
  let resolveHint: { ok: boolean; message: string } | null = null;
  let touched: Record<string, boolean> = {};
  let showTestHint = false;
  let showContinueHint = false;

  const touch = (field: 'name' | 'host' | 'port' | 'username' | 'password' | 'identity_source' | 'zone') => {
    touched = { ...touched, [field]: true };
  };

  const touchAllStep2 = () => {
    touched = {
      ...touched,
      name: true,
      host: true,
      port: true,
      username: true,
      password: true,
      identity_source: true,
      zone: true
    };

    showTestHint = !canTestConnection;
    showContinueHint = !canContinueStep2;
  };

  function resolveHostInput() {
    const value = (model.host ?? '').trim();
    if (!value) {
      resolveHint = { ok: false, message: 'Type un hostname ou une IP.' };
      return;
    }
    if (isValidIPv4(value)) {
      resolveHint = { ok: true, message: 'IP valide.' };
      return;
    }
    if (isValidHostname(value)) {
      resolveHint = { ok: true, message: 'Hostname valide.' };
      return;
    }
    resolveHint = { ok: false, message: 'Format hostname/IP invalide.' };
  }

  function resolveTestTarget(): string | null {
    const v = (model.host ?? '').trim();
    if (!v) return null;
    if (isValidIPv4(v) || isValidHostname(v)) return v;
    return null;
  }

  function normalizedHost(value?: string | null): string {
    return String(value ?? '').trim().toLowerCase();
  }

  $: currentNormalizedHost = normalizedHost(model.host);
  $: duplicateEndpoint = existingEndpoints.find((ep) => {
    const candidateHost = normalizedHost(String(ep?.host ?? ''));
    return Boolean(candidateHost && candidateHost === currentNormalizedHost);
  });

  /* =========================================================
     STEP 1 — TYPE
   ========================================================= */
  let selectedProtocol: 'smb' | null = null;

  function selectProtocol(p: 'smb') {
    selectedProtocol = p;
    model.protocol = p;
  }

  $: canContinueStep1 = selectedProtocol !== null;

  /* =========================================================
     NAVIGATION
  ========================================================= */
  function go(next: number) {
    direction = next > step ? 'forward' : 'back';
    step = next;
  }

  const panelIn = () => ({
    x: direction === 'forward' ? 40 : -40,
    duration: 220
  });

  function goStep2() {
    if (!canContinueStep1) return;
    go(2);
  }

  /* =========================================================
     DERIVED RULES
  ========================================================= */
  $: model.port ??= 445;

  const required = (v?: string | number | null) =>
    v !== undefined && v !== null && String(v).trim().length > 0;

  $: errName = Boolean(touched.name) && !required(model.name);
  $: errHost = Boolean(touched.host) && !required(model.host);
  $: errHostFormat =
    Boolean(touched.host) &&
    required(model.host) &&
    !isValidIPv4(model.host) &&
    !isValidHostname(model.host);
  $: errPort = Boolean(touched.port) && !required(model.port);
  $: errUsername = Boolean(touched.username) && !required(model.username);
  $: errPassword = Boolean(touched.password) && !required(model.password);
  $: errIdentitySource =
    requiresIdentitySource && Boolean(touched.identity_source) && !required(model.identity_source_id);
  $: errZone = Boolean(touched.zone) && !required(model.zone_id);

  $: if (showTestHint && canTestConnection) showTestHint = false;
  $: if (showContinueHint && canContinueStep2) showContinueHint = false;

  $: canContinueStep2 =
    required(model.name) &&
    required(model.zone_id) &&
    (!requiresIdentitySource || required(model.identity_source_id)) &&
    required(model.host) &&
    (isValidIPv4(model.host) || isValidHostname(model.host)) &&
    !duplicateEndpoint;

  function onIdentitySourceChange(event: Event) {
    const raw = (event.currentTarget as HTMLSelectElement).value;
    model.identity_source_id = raw ? Number(raw) : null;
    touch('identity_source');
  }

  $: canTestConnection =
    canContinueStep2 &&
    required(model.port) &&
    required(model.username) &&
    required(model.password);

  /* =========================================================
     STEP 2 — PROBE (V1.1)
  ========================================================= */
  type TestStatus = 'idle' | 'running' | 'success' | 'failed';
  let testStatus: TestStatus = 'idle';
  let testError: string | null = null;
  let connectionTested = false;
  let lastSuccessfulProbeAt: string | null = null;
  let lastSuccessfulProbeMessage: string | null = null;

  async function ensureSecretRef(
    mode: 'create' | 'edit' = 'create',
    options?: { clearPassword?: boolean }
  ): Promise<string | null> {
    const clearPassword = options?.clearPassword ?? true;
    const name = `storage-endpoint/${model.protocol}/${(model.host || model.name || 'endpoint').trim()}`;
    const resolved = await resolveCredentials(fetch, {
      username: model.username ?? null,
      password: model.password ?? null,
      secret_ref: model.secret_ref ?? null
    }, { secretName: name, mode });

    model.secret_ref = resolved.secret_ref ?? null;
    if (clearPassword) {
      // never keep plaintext password after resolving
      model.password = '';
    }
    return model.secret_ref;
  }

  function buildConnectProbeRequest(secretRef: string | null = model.secret_ref ?? null): ProbeRunRequest | null {
    const target = resolveTestTarget();
    if (!target) {
      return null;
    }
    return buildStorageEndpointConnectProbeRequest({
      protocol: model.protocol,
      host: target,
      port: model.port ?? 445,
      username: model.username ?? null,
      domain: extractDomainFromUsername(model.username),
      secretRef,
      password: secretRef ? null : model.password ?? null,
      discover: false,
      timeoutSec: 20,
      uiOrigin: 'wizard'
    });
  }

  $: if (step === 3 && discoverStatus === 'idle') {
    startDiscovery();
  }

  /* =========================================================
     STEP 3 — DISCOVERY
   ========================================================= */
  let governedRoots: string[] = [];
  let discoverStatus: 'idle' | 'running' | 'success' | 'failed' = 'idle';
  let discoverError: string | null = null;
  let rootsQuery = '';
  let detectedRoots: string[] = [];
  let alreadyGovernedRoots: string[] = [];

  const blockedRoots = ['SYSVOL', 'NETLOGON'];

  const normalizeRoot = (value: string) => value.trim();

  const rootLabel = (value: string) => {
    const normalized = normalizeRoot(value);
    const parts = normalized.split(/[\\/]+/).filter(Boolean);
    return parts[parts.length - 1] || normalized;
  };

  const isBlockedRoot = (value: string) =>
    blockedRoots.includes(rootLabel(value).toUpperCase());

  const isAlreadyGoverned = (value: string) => {
    const normalized = normalizeRoot(value);
    return alreadyGovernedRoots.some((root) => normalizeRoot(root) === normalized);
  };

  const isSelected = (value: string) => governedRoots.includes(normalizeRoot(value));

  const govern = (value: string) => {
    if (isAlreadyGoverned(value) || isBlockedRoot(value)) return;
    const normalized = normalizeRoot(value);
    if (governedRoots.includes(normalized)) return;
    governedRoots = [...governedRoots, normalized];
  };

  const ungovern = (value: string) => {
    const normalized = normalizeRoot(value);
    governedRoots = governedRoots.filter(root => root !== normalized);
  };

  const toggleGovern = (value: string) => {
    if (isAlreadyGoverned(value) || isBlockedRoot(value)) return;
    if (isSelected(value)) {
      ungovern(value);
      return;
    }
    govern(value);
  };

  const selectAllFiltered = () => {
    const selectable = filteredDetectedRoots
      .filter(root => !isAlreadyGoverned(root))
      .filter(root => !isBlockedRoot(root));
    const merged = new Set([...governedRoots, ...selectable.map(normalizeRoot)]);
    governedRoots = Array.from(merged);
  };

  const clearSelection = () => {
    governedRoots = [];
  };

  const invertSelection = () => {
    const next = new Set(governedRoots);
    for (const root of filteredDetectedRoots) {
      if (isAlreadyGoverned(root) || isBlockedRoot(root)) continue;
      const normalized = normalizeRoot(root);
      if (next.has(normalized)) next.delete(normalized);
      else next.add(normalized);
    }
    governedRoots = Array.from(next);
  };

  type RootStatusFilter = 'all' | 'available' | 'selected' | 'already_governed';
  let rootStatusFilter: RootStatusFilter = 'available';
  let rootPage = 1;
  let rootsPerPage = 8;

  $: filteredDetectedRoots = (() => {
    const query = rootsQuery.trim().toLowerCase();
    if (!query) return detectedRoots;
    return detectedRoots.filter(root => root.toLowerCase().includes(query));
  })();

  $: visibleDetectedRoots = filteredDetectedRoots.filter(root => !isBlockedRoot(root));
  $: selectableDetectedRoots = visibleDetectedRoots.filter((root) => !isAlreadyGoverned(root));
  $: selectedVisibleRoots = visibleDetectedRoots.filter((root) => isSelected(root));
  $: rootRows = visibleDetectedRoots.filter((root) => {
    if (rootStatusFilter === 'selected') return isSelected(root);
    if (rootStatusFilter === 'already_governed') return isAlreadyGoverned(root);
    if (rootStatusFilter === 'available') return !isAlreadyGoverned(root) && !isBlockedRoot(root);
    return true;
  });
  $: totalRootPages = Math.max(1, Math.ceil(rootRows.length / rootsPerPage));
  $: if (rootPage > totalRootPages) rootPage = totalRootPages;
  $: paginatedRootRows = rootRows.slice((rootPage - 1) * rootsPerPage, rootPage * rootsPerPage);
  $: rootRangeStart = rootRows.length === 0 ? 0 : (rootPage - 1) * rootsPerPage + 1;
  $: rootRangeEnd = Math.min(rootPage * rootsPerPage, rootRows.length);
  $: selectedPreviewRoots = governedRoots.slice(0, 4);
  $: hiddenSelectedCount = Math.max(0, governedRoots.length - selectedPreviewRoots.length);
  $: endpointHostLabel = String(model.host ?? '').trim() || 'Storage endpoint';
  $: lastScanLabel =
    discoverStatus === 'running'
      ? 'running'
      : discoverStatus === 'success'
        ? 'just now'
        : discoverStatus === 'failed'
          ? 'failed'
          : 'not scanned';

  async function startDiscovery() {
    if (!canContinueStep2) return;

    discoverStatus = 'running';
    discoverError = null;
    detectedRoots = [];
    alreadyGovernedRoots = [];
    jobsStore.startJob(wizardDiscoveryJobInput(), {
      message: 'Discovery running'
    });

    try {
      const secretRef = await ensureSecretRef('create');

      const target = resolveTestTarget();
      if (!target) {
        discoverStatus = 'failed';
        discoverError = 'Hostname / IP invalide';
        jobsStore.failJob(wizardDiscoveryJobInput(), {
          message: discoverError,
          error: discoverError
        });
        return;
      }

      const { job_id } = await runProbeJob(fetch, {
        kind: 'storage-endpoint',
        protocol: model.protocol,
        scope: 'read',
        target: {
          host: target,
          port: model.port
        },
        auth: {
          mode: 'ntlm',
          username: model.username,
          domain: extractDomainFromUsername(model.username),
          secret_ref: secretRef ?? undefined,
          password: secretRef ? undefined : model.password
        },
        options: {
          timeout_sec: 30,
          discover: true
        },
        context: { ui_origin: 'wizard' }
      });

      const polled = await pollProbeJob(fetch, job_id, {
        intervalMs: 3000,
        intervalMsByAttempt: (attempt) => (attempt < 2 ? 3000 : attempt < 6 ? 5000 : 8000)
      });

      if (polled.status === 'success') {
        const job = polled.payload as { result?: { details?: { roots?: string[] }; roots?: string[] } };
        const roots =
          (job?.result?.details?.roots as string[]) ||
          (job?.result?.roots as string[]) ||
          [];
        detectedRoots = Array.isArray(roots) ? roots : [];
        discoverStatus = 'success';
        lastSuccessfulProbeAt = new Date().toISOString();
        lastSuccessfulProbeMessage = `discovery_ok:${detectedRoots.length}`;
        jobsStore.succeedJob(wizardDiscoveryJobInput(), {
          message: 'Discovery success',
          summary: {
            rootsCount: detectedRoots.length
          },
          payload: job
        });
      } else {
        discoverStatus = 'failed';
        discoverError = polled.errorMessage ?? 'Discovery failed';
        jobsStore.failJob(wizardDiscoveryJobInput(), {
          message: discoverError,
          error: discoverError,
          payload: polled.payload
        });
      }
    } catch (e) {
      discoverStatus = 'failed';
      discoverError = e?.message ?? 'Unable to run discovery';
      jobsStore.failJob(wizardDiscoveryJobInput(), {
        message: discoverError,
        error: discoverError
      });
    }
  }

  /* =========================================================
     FINISH
  ========================================================= */
  async function finish() {
    if (!model.name) return;
    if (!required(model.zone_id)) {
      touch('zone');
      toast.error('A zone is required to create a storage endpoint.');
      return;
    }

    try {
      const secretRef = await ensureSecretRef('create');

      const created = await createStorageEndpoint(fetch, {
        name: model.name,
        description: model.description ?? null,
        endpoint_type: model.protocol,
        protocol: model.protocol,
        identity_source_id: model.identity_source_id ?? null,
        host: model.host ?? null,
        port: model.port ?? null,
        auth_type: 'ntlm',
        bind_dn: model.username ?? null,
        bind_password_ref: secretRef,
        zone_id: Number(model.zone_id),
        is_active: true,
        status: 'active',
        last_probe_status: lastSuccessfulProbeAt ? 'success' : null,
        last_probe_at: lastSuccessfulProbeAt,
        last_probe_message: lastSuccessfulProbeMessage
      });

      let createdRoots = 0;
      let failedRoots = 0;

      if (governedRoots.length > 0) {
        const res = await Promise.allSettled(
          governedRoots.map(locator =>
            createStorageRoot(fetch, {
              storage_endpoint_id: created.id,
              name: locator.split('\\').pop() || locator,
              root_path: locator,
              status: 'active'
            })
          )
        );

        for (const r of res) r.status === 'fulfilled' ? createdRoots++ : failedRoots++;
      }

      if (discoverStatus === 'success') {
        try {
          await syncStorageRootDiscoveryForEndpoint(fetch, created.id, {
            discovered_at: lastSuccessfulProbeAt ?? new Date().toISOString(),
            roots: detectedRoots
          });
        } catch (syncError) {
          console.warn('storage_endpoint_wizard.discovery_sync_failed', syncError);
          toast.warning('Storage roots were created, but discovery sync must be refreshed.');
        }
      }

      toast.success('Storage endpoint created.');
      dispatch('done', { id: created.id, created_roots: createdRoots, failed_roots: failedRoots });

      if (onDone) onDone();
      else if (isPage) goto('/admin/storage-endpoints');
    } catch (e) {
      toast.error(e?.message ?? 'Creation failed');
    }
  }
</script>

<!-- =========================================================
     WIZARD ROOT
========================================================= -->
 <div class="se-wizard b2s-wizard" class:page={isPage} class:se-wizard--modal={!isPage}>
   <div class="se-wizard-shell b2s-wizard-shell">
    <!-- HEADER -->
    <div class="se-wizard-header">
      <h1 id="storage-endpoint-wizard-title">
        {isPage ? 'Create your first storage endpoint' : 'Create storage endpoint'}
      </h1>
      <p>
        {isPage
          ? 'This wizard will guide you step by step to connect your first storage system.'
          : 'Connect a storage system and select governed roots.'}
      </p>
    </div>

    <!-- STEPPER (short + dynamic segments) -->
    <div class="se-stepper b2s-wizard-stepper" aria-label="Wizard progress">
      <div class="se-step b2s-wizard-step">
        <div class="num" class:active={step >= 1}>1</div>
        <div class="label" class:active={step >= 1}>Type</div>
      </div>

      <div class="se-line" class:active={step >= 2} aria-hidden="true"></div>

      <div class="se-step b2s-wizard-step">
        <div class="num" class:active={step >= 2}>2</div>
        <div class="label" class:active={step >= 2}>Connection</div>
      </div>

      <div class="se-line" class:active={step >= 3} aria-hidden="true"></div>

      <div class="se-step b2s-wizard-step">
        <div class="num" class:active={step >= 3}>3</div>
        <div class="label" class:active={step >= 3}>Governance</div>
      </div>
    </div>

    <!-- CARD -->
    <div class="se-card">
      <!-- STEP 1 -->
      {#if step === 1}
        <div
          class="se-step-panel se-step-panel--intro"
          in:fly={panelIn()}
          out:fade={{ duration: 120 }}
        >
          <h2>Choose Your Provider</h2>

          <div class="se-type-grid">
            <!-- SMB (enabled) -->
            <button
              type="button"
              class="se-type-card"
              class:selected={selectedProtocol === 'smb'}
              on:click={() => selectProtocol('smb')}
            >
              <i class="bi bi-display icon smb" aria-hidden="true"></i>
              <strong>SMB</strong>
              <span>Windows / Samba shares</span>
            </button>

            <!-- S3 (disabled) -->
            <button
              type="button"
              class="se-type-card disabled"
              disabled
              aria-disabled="true"
              title="Coming soon"
            >
              <i class="bi bi-box-seam icon s3" aria-hidden="true"></i>
              <strong>S3</strong>
              <span>Coming soon</span>
            </button>

            <!-- Azure Blob (disabled) -->
            <button
              type="button"
              class="se-type-card disabled"
              disabled
              aria-disabled="true"
              title="Coming soon"
            >
              <i class="bi bi-cloud icon azure" aria-hidden="true"></i>
              <strong>Azure Blob</strong>
              <span>Coming soon</span>
            </button>

            <!-- NFS (disabled) -->
            <button
              type="button"
              class="se-type-card disabled"
              disabled
              aria-disabled="true"
              title="Coming soon"
            >
              <i class="bi bi-hdd-network icon nfs" aria-hidden="true"></i>
              <strong>NFS</strong>
              <span>Coming soon</span>
            </button>
          </div>

          <div class="se-actions center">
            <button
              class="primary"
              disabled={!canContinueStep1}
              on:click={goStep2}
            >
              Continue
            </button>
          </div>

          {#if !canContinueStep1}
            <p class="se-hint">Select a type to continue.</p>
          {/if}
        </div>
      {/if}

      <!-- STEP 2 -->
      {#if step === 2}
        <div
          class="se-step-panel"
          in:fly={{ x: direction === 'forward' ? 40 : -40, duration: 220 }}
          out:fade
        >
          <h2>Connection</h2>

          <!-- SELECTED TYPE SUMMARY -->
          <div class="se-selected-type">
            <i class="bi bi-display icon smb"></i>
            <div>
              <strong>SMB</strong>
              <span>Windows / Samba shares</span>
            </div>
          </div>

          <!-- IDENTITY -->
           <div class="se-form-block">
             <h3>Identity</h3>
  
              <div class="se-form-grid se-form-grid--identity">
                <div>
                  <label for="se-name">Name <span class="req">*</span></label>
                 <input
                   id="se-name"
                   class="se-input"
                   class:invalid={errName}
                   bind:value={model.name}
                   placeholder="Main file server"
                   on:blur={() => touch('name')}
                 />
                {#if errName}
                  <div class="se-field-error">Name is required.</div>
                {/if}
              </div>

              <div>
                <label for="se-description">Description</label>
                <input
                  id="se-description"
                  class="se-input"
                  bind:value={model.description}
                  placeholder={'Production SMB storage'}
                />
              </div>
            </div>
          </div>

          <!-- ZONE -->
          <div class="se-form-block">
            <h3>Zone</h3>

            <div class="se-form-grid se-form-grid--identity">
              <div>
                 <label for="se-zone">Existing zone <span class="req">*</span></label>
                 <select
                   id="se-zone"
                   class="se-input"
                   class:invalid={errZone}
                   bind:value={model.zone_id}
                   disabled={lockZone}
                   on:blur={() => touch('zone')}
                 >
                  <option value={null} disabled>Select a zone</option>
                  {#each zones as z (z.id)}
                    <option value={z.id}>{z.name}</option>
                  {/each}
                </select>
                {#if zonesLoading}
                  <div class="se-field-hint">Loading zones…</div>
                {/if}
                {#if zonesError}
                  <div class="se-field-error">{zonesError}</div>
                {/if}
                {#if errZone}
                  <div class="se-field-error">Zone is required.</div>
                {/if}
                {#if !zonesLoading && !zonesError && zones.length === 0}
                  <div class="se-field-error">Create a zone before adding a storage endpoint.</div>
                {/if}
              </div>

              <div>
                <label for="se-identity-source">Identity source (AD)</label>
                <select
                  id="se-identity-source"
                  class="se-input"
                  class:invalid={errIdentitySource}
                  value={model.identity_source_id ?? ''}
                  on:change={onIdentitySourceChange}
                  on:blur={() => touch('identity_source')}
                >
                  <option value="">No identity source (optional)</option>
                  {#each activeAdIdentitySources as src (src.id)}
                    <option value={src.id}>{src.name ?? `Source #${src.id}`}</option>
                  {/each}
                </select>
                {#if identitySourcesLoading}
                  <div class="se-field-hint">Loading identity sources…</div>
                {/if}
                {#if identitySourcesError}
                  <div class="se-field-error">{identitySourcesError}</div>
                {/if}
                {#if !identitySourcesLoading && !identitySourcesError && activeAdIdentitySources.length === 0}
                  <div class="se-field-hint">No active AD identity source available (optional field).</div>
                {/if}
                {#if errIdentitySource}
                  <div class="se-field-error">Identity source is required.</div>
                {/if}
              </div>
            </div>
          </div>

          <!-- TARGET -->
           <div class="se-form-block">
             <h3>Target</h3>
 
              <div class="se-form-grid se-form-grid--target">
              <div>
                <label for="se-host">Hostname / IP <span class="req">*</span></label>
               <div class="b2s-input-with-action">
                 <input
                   id="se-host"
                   class="se-input"
                   class:invalid={errHost || errHostFormat}
                   bind:value={model.host}
                   placeholder="fileserver.domain.local ou 10.0.0.12"
                   on:blur={() => touch('host')}
                 />
                 <button
                   class="b2s-input-action"
                   type="button"
                   aria-label="Resolve host"
                   on:click={resolveHostInput}
                 >
                   <i class="bi bi-search" aria-hidden="true"></i>
                 </button>
               </div>
               {#if errHost}
                 <div class="se-field-error">Hostname/IP is required.</div>
               {/if}
               {#if errHostFormat}
                 <div class="se-field-error">Invalid hostname/IP.</div>
               {/if}
               {#if duplicateEndpoint}
                 <div class="se-field-error">A file server with the same IP/hostname already exists.</div>
               {/if}
               {#if resolveHint}
                 <div class={`se-field-hint ${resolveHint.ok ? 'ok' : ''}`}>{resolveHint.message}</div>
               {/if}
             </div>

              <div>
                <label for="se-port">Port <span class="req">*</span></label>
                <input
                  id="se-port"
                  class="se-input"
                  type="number"
                  class:invalid={errPort}
                  bind:value={model.port}
                  on:blur={() => touch('port')}
                />
                {#if errPort}
                  <div class="se-field-error">Port is required.</div>
                {/if}
              </div>
            </div>
          </div>

          <!-- CREDENTIALS -->
           <div class="se-form-block">
             <h3>Credentials</h3>
 
              <div class="se-form-grid se-form-grid--creds">
                <div>
                  <label for="se-username">Username <span class="req">*</span></label>
                 <input
                   id="se-username"
                   class="se-input"
                   class:invalid={errUsername}
                   bind:value={model.username}
                   placeholder="DOMAIN\\service-account"
                   on:blur={() => touch('username')}
                 />
                {#if errUsername}
                  <div class="se-field-error">Username is required.</div>
                {/if}
              </div>

              <div>
                <label for="se-password">Password <span class="req">*</span></label>
                <div class="b2s-input-with-action">
                  <input
                    id="se-password"
                    class="se-input"
                    type={showPassword ? 'text' : 'password'}
                    class:invalid={errPassword}
                    bind:value={model.password}
                    on:blur={() => touch('password')}
                  />
                  <button
                    class="b2s-input-action"
                    type="button"
                    tabindex="-1"
                    aria-label={showPassword ? 'Hide password' : 'Show password'}
                    on:click={() => (showPassword = !showPassword)}
                  >
                    <i class={`bi ${showPassword ? 'bi-eye-slash' : 'bi-eye'}`} aria-hidden="true"></i>
                  </button>
                </div>
                {#if errPassword}
                  <div class="se-field-error">Password is required.</div>
                {/if}
              </div>
            </div>

            {#if showTestHint}
              <p class="se-hint error">
                Fill all fields (except description) to test the connection.
              </p>
            {/if}

            {#if showContinueHint}
              <p class="se-hint error">
                Name, zone and Hostname/IP are required to continue.
              </p>
            {/if}
          </div>

          <!-- TEST CONNECTION -->
          <div class="se-test-connection">
            <RunProbeButton
              fetchFn={fetch}
              requestFactory={async () => {
                const secretRef = await ensureSecretRef('create', { clearPassword: false });
                return buildConnectProbeRequest(secretRef);
              }}
              label="Run Probe"
              busyLabel="Running probe…"
              fullWidth={true}
              showIcon={true}
              iconClass="bi bi-activity"
              busyIconClass="bi bi-hourglass-split"
              buttonClass={`se-run-probe-btn sed-btn sed-btn--secondary ${testStatus === 'success' ? 'is-success' : ''}`}
              hideSuccessPanel={true}
              disabled={!canTestConnection}
              beforeRun={async () => {
                testStatus = 'running';
                testError = null;
                lastSuccessfulProbeAt = null;
                lastSuccessfulProbeMessage = null;
                jobsStore.startJob(wizardProbeJobInput(), {
                  message: 'Probe running'
                });
              }}
              on:done={(e) => {
                testStatus = e.detail.ok ? 'success' : 'failed';
                connectionTested = Boolean(e.detail.ok);
                testError = e.detail.ok ? null : (e.detail.error?.message ?? 'Connection test failed');

                if (e.detail.ok) {
                  lastSuccessfulProbeAt = new Date().toISOString();
                  lastSuccessfulProbeMessage = 'probe_ok';
                  jobsStore.succeedJob(wizardProbeJobInput(), {
                    message: 'Probe OK',
                    summary: {
                      status: e.detail.status,
                      jobId: e.detail.jobId
                    }
                  });
                } else {
                  jobsStore.failJob(wizardProbeJobInput(), {
                    message: testError,
                    error: testError,
                    payload: e.detail.error ?? null
                  });
                }

                if (e.detail.ok) {
                  toast.success('Probe OK');
                }
              }}
            />
          </div>

          <!-- ACTIONS -->
          <div class="se-actions between">
            <button class="secondary" on:click={() => go(1)}>
              Back
            </button>

            <div class="se-actions-right">
              <button
                class="primary"
                disabled={!connectionTested || !canContinueStep2}
                on:click={() => {
                  touchAllStep2();
                  if (!canContinueStep2) return;
                  go(3);
                }}
              >
                Continue
              </button>
            </div>
          </div>
        </div>
      {/if}

      <!-- STEP 3 -->
      {#if step === 3}
        <div
          class="se-step-panel se-governance-step"
          in:fly={panelIn()}
          out:fade={{ duration: 120 }}
        >
          <h2>Select governed roots</h2>

          {#if !connectionTested}
            <div class="se-info-block warning">
              <strong>Connection not tested</strong><br />
              Discovery will be executed during final validation.
            </div>
          {/if}

          <div class="se-gov-topline" aria-live="polite">
            <div class="se-gov-topline__item">
              <i class="bi bi-folder" aria-hidden="true"></i>
              <span>{visibleDetectedRoots.length} detected</span>
            </div>
            <span class="se-gov-topline__dot" aria-hidden="true"></span>
            <div class="se-gov-topline__item">
              <i class="bi bi-check-circle" aria-hidden="true"></i>
              <span>{governedRoots.length} selected</span>
            </div>
            <span class="se-gov-topline__dot" aria-hidden="true"></span>
            <div class="se-gov-topline__item">
              <i class="bi bi-clock" aria-hidden="true"></i>
              <span>Last scan: {lastScanLabel}</span>
            </div>
            <button
              class="se-gov-refresh"
              type="button"
              disabled={!connectionTested || discoverStatus === 'running'}
              on:click={startDiscovery}
            >
              <i class={`bi ${discoverStatus === 'running' ? 'bi-hourglass-split' : 'bi-arrow-clockwise'}`} aria-hidden="true"></i>
              {discoverStatus === 'running' ? 'Refreshing…' : 'Refresh'}
            </button>
          </div>

          {#if discoverStatus === 'failed'}
            <div class="se-info-block warning">
              <strong>Discovery failed</strong><br />
              {discoverError ?? 'Discovery failed'}
            </div>
          {/if}

          <div class="se-governance-layout">
            <section class="se-shares-card" aria-label="Detected shares">
              <div class="se-shares-toolbar">
                <div class="se-shares-search">
                  <i class="bi bi-search" aria-hidden="true"></i>
                  <input
                    placeholder="Search shares..."
                    value={rootsQuery}
                    on:input={(event) => {
                      rootsQuery = (event.currentTarget as HTMLInputElement).value;
                      rootPage = 1;
                    }}
                  />
                </div>

                <select
                  class="se-shares-filter"
                  value={rootStatusFilter}
                  on:change={(event) => {
                    rootStatusFilter = (event.currentTarget as HTMLSelectElement).value as RootStatusFilter;
                    rootPage = 1;
                  }}
                >
                  <option value="available">Availability: Available</option>
                  <option value="all">Availability: All</option>
                  <option value="selected">Availability: Selected</option>
                  <option value="already_governed">Availability: Integrated</option>
                </select>

                <button class="se-link se-link--quiet" type="button" on:click={clearSelection}>
                  Clear all
                </button>

                <button class="se-link se-link--right" type="button" on:click={selectAllFiltered}>
                  Select all {selectableDetectedRoots.length}
                </button>
              </div>

              {#if discoverStatus === 'success' && visibleDetectedRoots.length === 0 && alreadyGovernedRoots.length === 0}
                <div class="se-empty">
                  <strong>No root detected.</strong>
                  <div class="se-muted">Run discovery again or continue without roots.</div>
                </div>
              {:else}
                <div class="se-shares-table-wrap">
                  <table class="se-shares-table">
                    <thead>
                      <tr>
                        <th class="se-shares-table__check">
                          <input
                            type="checkbox"
                            aria-label="Select all eligible shares"
                            checked={selectableDetectedRoots.length > 0 && selectableDetectedRoots.every((root) => isSelected(root))}
                            on:change={(event) => {
                              if ((event.currentTarget as HTMLInputElement).checked) selectAllFiltered();
                              else clearSelection();
                            }}
                          />
                        </th>
                        <th class="se-shares-table__badge">State</th>
                        <th>Name <i class="bi bi-arrow-down-up" aria-hidden="true"></i></th>
                        <th>Path</th>
                      </tr>
                    </thead>
                    <tbody>
                      {#each paginatedRootRows as root}
                        <tr class:selected={isSelected(root)}>
                          <td class="se-shares-table__check">
                            <input
                              type="checkbox"
                              aria-label={`Select ${rootLabel(root)}`}
                              checked={isSelected(root)}
                              disabled={isAlreadyGoverned(root) || isBlockedRoot(root)}
                              on:change={() => toggleGovern(root)}
                            />
                          </td>
                          <td class="se-shares-table__badge">
                            {#if isAlreadyGoverned(root)}
                              <span class="se-root-availability se-root-availability--managed">
                                {managedRootBadgeLabel}
                              </span>
                            {:else}
                              <span class="se-root-availability se-root-availability--available">
                                {availableRootBadgeLabel}
                              </span>
                            {/if}
                          </td>
                          <td>
                            <button
                              type="button"
                              class="se-share-name"
                              disabled={isAlreadyGoverned(root) || isBlockedRoot(root)}
                              on:click={() => toggleGovern(root)}
                            >
                              <i class="bi bi-folder" aria-hidden="true"></i>
                              <span>{rootLabel(root)}</span>
                            </button>
                          </td>
                          <td class="se-share-path mono">{root}</td>
                        </tr>
                      {/each}
                    </tbody>
                  </table>
                </div>

                {#if rootRows.length === 0}
                    <div class="se-empty">
                      <strong>No match.</strong>
                      <div class="se-muted">Change the filter or clear it.</div>
                    </div>
                {/if}

                <div class="se-shares-pagination">
                  <span>{rootRangeStart}-{rootRangeEnd} of {rootRows.length}</span>
                  <div class="se-shares-pages" aria-label="Shares pagination">
                    <button
                      type="button"
                      disabled={rootPage === 1}
                      on:click={() => (rootPage = Math.max(1, rootPage - 1))}
                      aria-label="Previous page"
                    >
                      <i class="bi bi-chevron-left" aria-hidden="true"></i>
                    </button>
                    <button type="button" class:active={rootPage === 1} on:click={() => (rootPage = 1)}>1</button>
                    {#if totalRootPages > 1}
                      <button type="button" class:active={rootPage === 2} on:click={() => (rootPage = Math.min(2, totalRootPages))}>2</button>
                    {/if}
                    {#if totalRootPages > 2}
                      <button type="button" class:active={rootPage === 3} on:click={() => (rootPage = Math.min(3, totalRootPages))}>3</button>
                    {/if}
                    {#if totalRootPages > 4}
                      <span>...</span>
                      <button type="button" class:active={rootPage === totalRootPages} on:click={() => (rootPage = totalRootPages)}>{totalRootPages}</button>
                    {/if}
                    <button
                      type="button"
                      disabled={rootPage === totalRootPages}
                      on:click={() => (rootPage = Math.min(totalRootPages, rootPage + 1))}
                      aria-label="Next page"
                    >
                      <i class="bi bi-chevron-right" aria-hidden="true"></i>
                    </button>
                  </div>
                  <select
                    class="se-shares-page-size"
                    value={rootsPerPage}
                    on:change={(event) => {
                      rootsPerPage = Number((event.currentTarget as HTMLSelectElement).value);
                      rootPage = 1;
                    }}
                  >
                    <option value="8">8 per page</option>
                    <option value="12">12 per page</option>
                    <option value="20">20 per page</option>
                  </select>
                </div>
              {/if}
            </section>

            <aside class="se-selection-card" aria-label="Selection summary">
              <h3>Selection summary</h3>
              <div class="se-selection-count">
                <strong>{governedRoots.length}</strong>
                <span>selected</span>
                {#if governedRoots.length > 0}
                  <button type="button" on:click={clearSelection}>Clear all</button>
                {/if}
              </div>

              {#if governedRoots.length === 0}
                <div class="se-selection-empty">
                  No governed root selected.
                </div>
              {:else}
                <div class="se-selected-list">
                  {#each selectedPreviewRoots as root}
                    <div class="se-selected-item">
                      <i class="bi bi-folder-fill" aria-hidden="true"></i>
                      <div>
                        <strong>{rootLabel(root)}</strong>
                        <span class="mono">{root}</span>
                      </div>
                      <button type="button" aria-label={`Remove ${rootLabel(root)}`} on:click={() => ungovern(root)}>
                        <i class="bi bi-x" aria-hidden="true"></i>
                      </button>
                    </div>
                  {/each}
                </div>

                {#if hiddenSelectedCount > 0}
                  <button type="button" class="se-selection-more">
                    <i class="bi bi-plus" aria-hidden="true"></i>
                    {hiddenSelectedCount} more
                    <i class="bi bi-chevron-down" aria-hidden="true"></i>
                  </button>
                {/if}
              {/if}

              <div class="se-governance-note">
                <i class="bi bi-info-circle-fill" aria-hidden="true"></i>
                <span>
                  Governance will be initialized after endpoint creation. Access profiles and
                  guardians can be configured next.
                </span>
              </div>

              <div class="se-created-box">
                <h4>What will be created</h4>
                <div class="se-created-row">
                  <i class="bi bi-hdd-rack" aria-hidden="true"></i>
                  <span>Storage endpoint</span>
                  <strong>{endpointHostLabel}</strong>
                </div>
                <div class="se-created-row">
                  <i class="bi bi-folder" aria-hidden="true"></i>
                  <span>Governed roots</span>
                  <strong>{governedRoots.length} roots</strong>
                </div>
              </div>
            </aside>
          </div>

          <div class="se-actions split se-governance-footer">
            <button class="secondary" on:click={() => go(2)}>Back</button>
            <div class="se-actions-right">
              <button class="secondary se-skip-roots-btn" on:click={finish}>
                Skip roots
              </button>
              <button class="primary se-create-endpoint-btn" on:click={finish}>
                Create storage endpoint{governedRoots.length > 0 ? ` with ${governedRoots.length} roots` : ''}
                <i class="bi bi-chevron-right" aria-hidden="true"></i>
              </button>
            </div>
          </div>
        </div>
      {/if}
    </div>
  </div>
</div>

<style>
  /* minimal, non-invasive visual validation */
  .req {
    opacity: 0.8;
  }

  .se-input.invalid {
    border-color: rgba(220, 53, 69, 0.75) !important;
    box-shadow: 0 0 0 2px rgba(220, 53, 69, 0.12);
  }

  .se-field-error {
    margin-top: 6px;
    font-size: 12px;
    line-height: 1.2;
    color: rgba(220, 53, 69, 0.95);
  }

  .se-field-hint {
    margin-top: 6px;
    font-size: 12px;
    color: #64748b;
    font-weight: 600;
  }

  .se-field-hint.ok {
    color: #15803d;
  }
</style>
