from __future__ import annotations

import json
import time
import socket
import logging
from pathlib import Path
from typing import Optional

from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel, Field

from ..logging_db import logging_store, normalize_level

router = APIRouter(prefix="/runtime", tags=["runtime"])

# Configure logger
logging.basicConfig(level=logging.DEBUG, format="%(asctime)s - %(message)s")
log = logging.getLogger("wizard")

# ============================================================
# 📦 PAYLOADS
# ============================================================

class RuntimeConfig(BaseModel):
    """
    Configuration globale générée par le Wizard.
    Structure volontairement souple (évolutive).
    """
    db_root: Optional[dict] = None
    db_app: Optional[dict] = None
    db_name: str = "borntoshare"

    syslog: Optional[dict] = None
    smtp: Optional[dict] = None
    idp: Optional[dict] = None
    domain: Optional[dict] = None

    ports: Optional[dict] = None


class PortTestPayload(BaseModel):
    host: str = Field(..., description="Target host or IP")
    port: int = Field(..., description="Target port")
    protocol: str = Field("tcp", description="tcp or udp")


# ============================================================
# 🧩 GENERATE ANSIBLE RUNTIME PACK
# ============================================================

@router.post("/generate-ansible")
async def generate_ansible_pack(config: RuntimeConfig):
    """
    Génère le bundle runtime BornToShare :
      - b2s-runtime-manifest.json
      - inventory.ini
      - group_vars/all.yml
      - deploy_borntoshare.yml
    """
    out_dir = ensure_output_dir()

    # --------------------------------------------------------
    # 1️⃣ Manifest JSON
    # --------------------------------------------------------
    manifest_path = out_dir / "b2s-runtime-manifest.json"
    manifest_path.write_text(
        json.dumps(config.dict(), indent=2, ensure_ascii=False),
        encoding="utf-8",
    )

    # --------------------------------------------------------
    # 2️⃣ Inventory minimal
    # --------------------------------------------------------
    inventory_path = out_dir / "inventory.ini"
    inventory_path.write_text(
        "[borntoshare]\nlocalhost ansible_connection=local\n",
        encoding="utf-8",
    )

    # --------------------------------------------------------
    # 3️⃣ group_vars/all.yml
    # --------------------------------------------------------
    group_vars_dir = out_dir / "group_vars"
    group_vars_dir.mkdir(exist_ok=True)

    db_root = config.db_root or {}
    db_app = config.db_app or {}
    ports = config.ports or {}

    group_all_content = f"""---
# ============================================================
# BornToShare – Runtime variables (generated by Wizard)
# ============================================================

# --------------------------
# DATABASE
# --------------------------
b2s_db_host: {db_root.get("host", "localhost")}
b2s_db_port: {db_root.get("port", 3306)}
b2s_db_name: {config.db_name}
b2s_db_user: {db_app.get("user", "b2s_app")}
b2s_db_password: "{db_app.get("password", "")}"

# --------------------------
# PORTS
# --------------------------
b2s_port_auth: {ports.get("auth", 8001)}
b2s_port_gov: {ports.get("governance", 8002)}
b2s_port_frontend: {ports.get("frontend", 8081)}
"""

    group_all_path = group_vars_dir / "all.yml"
    group_all_path.write_text(group_all_content, encoding="utf-8")

    # --------------------------------------------------------
    # 4️⃣ Playbook minimal
    # --------------------------------------------------------
    playbook_path = out_dir / "deploy_borntoshare.yml"

    playbook_content = """---
- name: Déployer BornToShare (Podman)
  hosts: borntoshare
  become: false
  vars_files:
    - group_vars/all.yml

  tasks:
    - name: Charger le manifest runtime
      ansible.builtin.set_fact:
        b2s_runtime: "{{ lookup('file', 'b2s-runtime-manifest.json') | from_json }}"

    - name: Créer réseau BornToShare
      containers.podman.podman_network:
        name: b2s_net
        state: present
"""

    playbook_path.write_text(playbook_content, encoding="utf-8")

    return {
        "ok": True,
        "message": "Pack Ansible généré",
        "files": [
            str(manifest_path),
            str(inventory_path),
            str(group_all_path),
            str(playbook_path),
        ],
    }


# ============================================================
# 🚦 TRIGGER DEPLOY (watcher / sidecar)
# ============================================================

@router.post("/trigger-deploy")
async def trigger_deploy():
    out_dir = ensure_output_dir()
    signal_path = out_dir / "run_services.signal"

    signal_path.write_text(
        f"trigger at {time.strftime('%Y-%m-%d %H:%M:%S')}",
        encoding="utf-8",
    )

    return {
        "ok": True,
        "message": "Signal de déploiement généré",
        "file": str(signal_path),
    }


# ============================================================
# 🔍 TEST PORT (TCP / UDP)
# ============================================================

@router.post("/test-port")
async def test_port(payload: PortTestPayload):
    """
    Test simple de connectivité réseau (TCP/UDP).
    """
    start = time.time()

    try:
        if payload.protocol == "tcp":
            with socket.create_connection(
                (payload.host, payload.port),
                timeout=1.5,
            ):
                pass
        else:
            sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            sock.sendto(b"ping", (payload.host, payload.port))
            sock.close()

        latency = round((time.time() - start) * 1000, 2)

        return {
            "ok": True,
            "latency_ms": latency,
        }

    except Exception as exc:
        return {
            "ok": False,
            "error": str(exc),
        }


# ============================================================
# 📚 LOGGING
# ============================================================

class LogRequest(BaseModel):
    level: str = Field(..., description="Log level (info, warning, error, etc.)")
    message: str = Field(..., description="Message de log à enregistrer")


class LoggingConfigPayload(BaseModel):
    level: str = Field("INFO", description="DEBUG|INFO|WARN|ERROR")
    retentionEnabled: bool = Field(True)
    retentionDays: int = Field(180, ge=1)


class LoggingPurgePayload(BaseModel):
    all: bool = Field(False)
    olderThanDays: Optional[int] = Field(None, ge=1)


class ActivityEventPayload(BaseModel):
    actor_type: str = Field("system", min_length=1, max_length=16)
    actor_id: Optional[int] = None
    actor_display: Optional[str] = None
    action: str = Field(..., min_length=1, max_length=128)
    outcome: str = Field("success", min_length=1, max_length=16)
    result: Optional[str] = Field(None, min_length=1, max_length=20)
    severity: Optional[str] = Field(None, min_length=1, max_length=20)
    event_category: Optional[str] = Field(None, max_length=32)
    event_scope: Optional[str] = Field(None, max_length=16)
    target_type: Optional[str] = Field(None, max_length=64)
    target_id: Optional[int] = None
    target_display: Optional[str] = None
    zone_id: Optional[int] = None
    root_id: Optional[int] = None
    endpoint_id: Optional[int] = None
    storage_root_id: Optional[int] = None
    entity_type: Optional[str] = Field(None, max_length=80)
    entity_id: Optional[str] = None
    context_json: Optional[dict] = None
    metadata_json: Optional[dict] = None
    correlation_id: Optional[str] = Field(None, max_length=64)


def _apply_runtime_level(level: str) -> str:
    normalized = normalize_level(level)
    py_level_name = "WARNING" if normalized == "WARN" else normalized
    py_level = getattr(logging, py_level_name, logging.INFO)
    logging.getLogger().setLevel(py_level)
    logging.getLogger("uvicorn").setLevel(py_level)
    logging.getLogger("uvicorn.error").setLevel(py_level)
    logging.getLogger("uvicorn.access").setLevel(py_level)
    return normalized


@router.get("/logging-config")
async def get_logging_config():
    try:
        return logging_store.get_config()
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Unable to load logging config: {exc}")


@router.put("/logging-config")
async def set_logging_config(payload: LoggingConfigPayload):
    try:
        saved = logging_store.save_config(
            level=payload.level,
            retention_enabled=payload.retentionEnabled,
            retention_days=payload.retentionDays,
        )
        _apply_runtime_level(saved["level"])
        return {"ok": True, **saved}
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Unable to save logging config: {exc}")


@router.get("/logs")
async def list_logs(
    limit: int = Query(default=100, ge=1, le=500),
    level: Optional[str] = Query(default=None),
):
    try:
        rows = logging_store.list_logs(limit=limit, level=level)
        return {"logs": rows}
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Unable to read logs: {exc}")


@router.post("/logs/purge")
async def purge_logs(payload: LoggingPurgePayload):
    try:
        deleted = logging_store.purge_logs(
            older_than_days=payload.olderThanDays,
            all_logs=payload.all,
        )
        return {"ok": True, "deleted": deleted}
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Unable to purge logs: {exc}")


@router.post("/activity/events")
async def create_activity_event(payload: ActivityEventPayload):
    try:
        request_id = None
        effective_target_type = payload.entity_type or payload.target_type
        effective_target_id: Optional[int] = payload.target_id
        if effective_target_id is None and payload.entity_id is not None:
            try:
                effective_target_id = int(payload.entity_id)
            except Exception:
                effective_target_id = None

        event_id = logging_store.write_activity_event(
            actor_type=payload.actor_type,
            actor_id=payload.actor_id,
            actor_display=payload.actor_display,
            action=payload.action,
            outcome=payload.result or payload.outcome,
            event_category=payload.event_category,
            event_scope=payload.event_scope,
            target_type=effective_target_type,
            target_id=effective_target_id,
            target_display=payload.target_display,
            metadata_json=payload.metadata_json or payload.context_json,
            request_id=request_id,
            correlation_id=payload.correlation_id,
            zone_id=payload.zone_id,
            root_id=payload.root_id if payload.root_id is not None else payload.storage_root_id,
            endpoint_id=payload.endpoint_id,
            severity=payload.severity,
        )
        return {"ok": True, "id": event_id}
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Unable to write activity event: {exc}")


@router.get("/activity/latest")
async def list_activity_latest(
    limit: int = Query(default=100, ge=1, le=500),
    actor_id: Optional[int] = Query(default=None),
    target_type: Optional[str] = Query(default=None),
    target_id: Optional[int] = Query(default=None),
    zone_id: Optional[int] = Query(default=None),
    root_id: Optional[int] = Query(default=None),
    endpoint_id: Optional[int] = Query(default=None),
    storage_root_id: Optional[int] = Query(default=None),
    event_category: Optional[str] = Query(default=None),
    event_scope: Optional[str] = Query(default=None),
    start_at: Optional[str] = Query(default=None),
    end_at: Optional[str] = Query(default=None),
):
    try:
        events = logging_store.list_activity_events(
            limit=limit,
            actor_id=actor_id,
            target_type=target_type,
            target_id=target_id,
            zone_id=zone_id,
            root_id=root_id if root_id is not None else storage_root_id,
            endpoint_id=endpoint_id,
            event_category=event_category,
            event_scope=event_scope,
            start_at=start_at,
            end_at=end_at,
        )
        return {"events": events}
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Unable to list activity events: {exc}")


@router.get("/activity/by-target")
async def list_activity_by_target(
    target_type: str = Query(...),
    target_id: Optional[int] = Query(default=None),
    limit: int = Query(default=200, ge=1, le=500),
):
    try:
        events = logging_store.list_activity_events(
            limit=limit,
            target_type=target_type,
            target_id=target_id,
        )
        return {"events": events}
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Unable to list activity by target: {exc}")


@router.get("/activity/by-actor")
async def list_activity_by_actor(
    actor_id: int = Query(...),
    limit: int = Query(default=200, ge=1, le=500),
):
    try:
        events = logging_store.list_activity_events(limit=limit, actor_id=actor_id)
        return {"events": events}
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Unable to list activity by actor: {exc}")

@router.post("/log")
async def log_event(log_data: LogRequest):
    """
    Route pour recevoir des logs et les enregistrer dans les fichiers ou les afficher.
    """
    level = log_data.level.lower()
    message = log_data.message

    if level == "info":
        log.info(message)
    elif level == "warning":
        log.warning(message)
    elif level == "error":
        log.error(message)
    else:
        raise HTTPException(status_code=400, detail="Niveau de log invalide. Utilisez 'info', 'warning', ou 'error'.")

    return {"message": "Log enregistré avec succès"}
