from __future__ import annotations

import json
import time
import socket
import logging
from pathlib import Path
from typing import Optional

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

router = APIRouter(prefix="/api/runtime", tags=["runtime"])

# Configure logger
logging.basicConfig(level=logging.DEBUG, format="%(asctime)s - %(message)s")
log = logging.getLogger("wizard")

# ============================================================
# 📦 PAYLOADS
# ============================================================

class RuntimeConfig(BaseModel):
    """
    Configuration globale générée par le Wizard.
    Structure volontairement souple (évolutive).
    """
    db_root: Optional[dict] = None
    db_app: Optional[dict] = None
    db_name: str = "borntoshare"

    syslog: Optional[dict] = None
    smtp: Optional[dict] = None
    idp: Optional[dict] = None
    domain: Optional[dict] = None

    ports: Optional[dict] = None


class PortTestPayload(BaseModel):
    host: str = Field(..., description="Target host or IP")
    port: int = Field(..., description="Target port")
    protocol: str = Field("tcp", description="tcp or udp")


# ============================================================
# 🧩 GENERATE ANSIBLE RUNTIME PACK
# ============================================================

@router.post("/generate-ansible")
async def generate_ansible_pack(config: RuntimeConfig):
    """
    Génère le bundle runtime BornToShare :
      - b2s-runtime-manifest.json
      - inventory.ini
      - group_vars/all.yml
      - deploy_borntoshare.yml
    """
    out_dir = ensure_output_dir()

    # --------------------------------------------------------
    # 1️⃣ Manifest JSON
    # --------------------------------------------------------
    manifest_path = out_dir / "b2s-runtime-manifest.json"
    manifest_path.write_text(
        json.dumps(config.dict(), indent=2, ensure_ascii=False),
        encoding="utf-8",
    )

    # --------------------------------------------------------
    # 2️⃣ Inventory minimal
    # --------------------------------------------------------
    inventory_path = out_dir / "inventory.ini"
    inventory_path.write_text(
        "[borntoshare]\nlocalhost ansible_connection=local\n",
        encoding="utf-8",
    )

    # --------------------------------------------------------
    # 3️⃣ group_vars/all.yml
    # --------------------------------------------------------
    group_vars_dir = out_dir / "group_vars"
    group_vars_dir.mkdir(exist_ok=True)

    db_root = config.db_root or {}
    db_app = config.db_app or {}
    ports = config.ports or {}

    group_all_content = f"""---
# ============================================================
# BornToShare – Runtime variables (generated by Wizard)
# ============================================================

# --------------------------
# DATABASE
# --------------------------
b2s_db_host: {db_root.get("host", "localhost")}
b2s_db_port: {db_root.get("port", 3306)}
b2s_db_name: {config.db_name}
b2s_db_user: {db_app.get("user", "b2s_app")}
b2s_db_password: "{db_app.get("password", "")}"

# --------------------------
# PORTS
# --------------------------
b2s_port_auth: {ports.get("auth", 8001)}
b2s_port_gov: {ports.get("governance", 8002)}
b2s_port_gateway: {ports.get("gateway", 8080)}
b2s_port_frontend: {ports.get("frontend", 8081)}
"""

    group_all_path = group_vars_dir / "all.yml"
    group_all_path.write_text(group_all_content, encoding="utf-8")

    # --------------------------------------------------------
    # 4️⃣ Playbook minimal
    # --------------------------------------------------------
    playbook_path = out_dir / "deploy_borntoshare.yml"

    playbook_content = """---
- name: Déployer BornToShare (Podman)
  hosts: borntoshare
  become: false
  vars_files:
    - group_vars/all.yml

  tasks:
    - name: Charger le manifest runtime
      ansible.builtin.set_fact:
        b2s_runtime: "{{ lookup('file', 'b2s-runtime-manifest.json') | from_json }}"

    - name: Créer réseau BornToShare
      containers.podman.podman_network:
        name: b2s_net
        state: present
"""

    playbook_path.write_text(playbook_content, encoding="utf-8")

    return {
        "ok": True,
        "message": "Pack Ansible généré",
        "files": [
            str(manifest_path),
            str(inventory_path),
            str(group_all_path),
            str(playbook_path),
        ],
    }


# ============================================================
# 🚦 TRIGGER DEPLOY (watcher / sidecar)
# ============================================================

@router.post("/trigger-deploy")
async def trigger_deploy():
    out_dir = ensure_output_dir()
    signal_path = out_dir / "run_services.signal"

    signal_path.write_text(
        f"trigger at {time.strftime('%Y-%m-%d %H:%M:%S')}",
        encoding="utf-8",
    )

    return {
        "ok": True,
        "message": "Signal de déploiement généré",
        "file": str(signal_path),
    }


# ============================================================
# 🔍 TEST PORT (TCP / UDP)
# ============================================================

@router.post("/test-port")
async def test_port(payload: PortTestPayload):
    """
    Test simple de connectivité réseau (TCP/UDP).
    """
    start = time.time()

    try:
        if payload.protocol == "tcp":
            with socket.create_connection(
                (payload.host, payload.port),
                timeout=1.5,
            ):
                pass
        else:
            sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            sock.sendto(b"ping", (payload.host, payload.port))
            sock.close()

        latency = round((time.time() - start) * 1000, 2)

        return {
            "ok": True,
            "latency_ms": latency,
        }

    except Exception as exc:
        return {
            "ok": False,
            "error": str(exc),
        }


# ============================================================
# 📚 LOGGING
# ============================================================

class LogRequest(BaseModel):
    level: str = Field(..., description="Log level (info, warning, error, etc.)")
    message: str = Field(..., description="Message de log à enregistrer")

@router.post("/api/log")
async def log_event(log_data: LogRequest):
    """
    Route pour recevoir des logs et les enregistrer dans les fichiers ou les afficher.
    """
    level = log_data.level.lower()
    message = log_data.message

    if level == "info":
        log.info(message)
    elif level == "warning":
        log.warning(message)
    elif level == "error":
        log.error(message)
    else:
        raise HTTPException(status_code=400, detail="Niveau de log invalide. Utilisez 'info', 'warning', ou 'error'.")

    return {"message": "Log enregistré avec succès"}
