services:
  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: Containerfile
    image: b2s-auth-service-vnext-stateless:latest

    restart: unless-stopped

    environment:
      # Mode de l'application
      - APP_ENV=dev
      # 👉 Logs BornToShare
      - B2S_DEBUG=true
      - B2S_LOG_LEVEL=trace

    # 🔥 Auth-service NE DOIT PAS être exposé au public
    expose:
      - "8000"

    networks:
      - app_net

networks:
  app_net:
    external: true
